### ISSUE TITLE
Nil pointer

### ISSUE THREAD

**Issue by mtricht** [swordbeta/trello-burndown#4]
```
2016/12/29 14:21:01 watcher.go:81: Checking board ID #AaV7RpBq
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x46703e]
goroutine 132408 [running]:
panic(0xa6ccc0, 0xc82000a080)
	/usr/lib/go/src/runtime/panic.go:481 +0x3e6
github.com/swordbeta/trello-burndown/src/backend.getBoard(0xc8207ced18, 0x8, 0x0, 0x0, 0x0)
	/root/gocode/src/github.com/swordbeta/trello-burndown/src/backend/watcher.go:132 +0x59e
github.com/swordbeta/trello-burndown/src/backend.Run(0xc8207ced18, 0x8)
	/root/gocode/src/github.com/swordbeta/trello-burndown/src/backend/watcher.go:82 +0x15b
created by github.com/swordbeta/trello-burndown/src/backend.runBoards
	/root/gocode/src/github.com/swordbeta/trello-burndown/src/backend/watcher.go:76 +0x4c9
```

**Comment by mtricht** [comment]
Haven't seen it happen again
